import type { Step } from '../types.js';

export interface CommentData {
  prNumber: number;
  steps: Step[];
  artifactUrl: string | null;
  gifUrl: string | null;
  durationSec: number;
}

export function formatComment(data: CommentData): string {
  const lines: string[] = [
    `## 🎬 PRessPlay Demo — PR #${data.prNumber}`,
    '',
    '> Automated demo of frontend changes',
    '',
  ];

  if (data.gifUrl) {
    lines.push(`![Demo GIF](${data.gifUrl})`, '');
  }

  if (data.artifactUrl) {
    lines.push(`📹 [Full video (MP4)](${data.artifactUrl})`, '');
  }

  const stepsWithNotes = data.steps.filter((s) => s.note);
  if (stepsWithNotes.length > 0) {
    lines.push('### What\'s shown:', '');
    stepsWithNotes.forEach((step, i) => {
      lines.push(`${i + 1}. **${step.action}**${step.url ? ` ${step.url}` : ''}${step.selector ? ` \`${step.selector}\`` : ''} — *"${step.note}"*`);
    });
    lines.push('');
  }

  lines.push(
    '<details>',
    '<summary>Recording details</summary>',
    '',
    `- Video: ${data.durationSec}s`,
    `- Steps: ${data.steps.length}`,
    '',
    '</details>',
    '',
    '---',
    '*Generated by [PRessPlay](https://github.com/yourorg/pressplay)*',
  );

  return lines.join('\n');
}
